name: Component Detection
on:
  workflow_dispatch:
  push:

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet restore
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@feature/handle-null-purls
